name: Patrick Blackard
favicon: null
layout_spectrum: 0.8111529187299311
typography_spectrum: 0.2542624396737665
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2680341068189591
  lightness: 0.6118640089407563
  saturation: 0.6323900707066059
  rhythmicContrast: 0.7463411448989064
purpose: []
